import React from "react";
import Layout from "../components/Layout/Layout";
import '../styles/globals.css'
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
      <div>
          <Head>
              <title>iCare</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />\
          </Head>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster:300,400,500,700&display=swap" />
          <Layout>
            <Component {...pageProps} />
          </Layout>
      </div>
      )
}

export default MyApp
