import React, {Fragment} from "react";
import '../styles/globals.css'
import Head from "next/head";
import CssBaseline from "@mui/material/CssBaseline";

function MyApp({ Component, pageProps }) {
  return (
      <Fragment>
          <Head>
              <title>iCare Platform</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />\
          </Head>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster:300,400,500,700&display=swap" />
            <CssBaseline />
            <Component {...pageProps} />
      </Fragment>
      )
}

export default MyApp
