import Head from 'next/head'
import styles from '../styles/Page.module.css'
import DashboardPage from "./dashboard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>iCare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1> INDEX JS</h1>
      </main>
    </div>
  )
}
